# Don't change the line below!
#! oxygen_storefront_id: 622885

name: Storefront 622885
on: [push]

permissions:
  contents: read
  deployments: write

jobs:
  checkout-verify-and-deploy:
    name: Checkout, Verify & Deploy
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12'
          check-latest: true
          cache: 'npm'

      - name: Install dependencies
        id: 'install-dependencies'
        run: npm ci

      - name: ESLint check
        id: eslint
        run: npm run lint

      - name: Run tests
        id: tests
        run: npm test

      - name: Build and Publish to Oxygen
        id: deploy
        uses: shopify/oxygenctl-action@v4
        with:
          oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_622885 }}
          build_command: "HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL npm run build"

      # Create GitHub Deployment
      - name: Create GitHub Deployment
        uses: shopify/github-deployment-action@v1
        if: always()
        with:
          token: ${{ github.token }}
          environment: 'preview'
          preview_url: ${{ steps.deploy.outputs.url }}
          description: ${{ github.event.head_commit.message }}
