# Don't change the line below!
#! oxygen_storefront_id: 622885

name: Storefront 622885
on:
- push
permissions:
  contents: read
  deployments: write
jobs:
  checkout-verify-and-deploy:
    name: Checkout, Verify & Deploy
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        check-latest: true
        cache: npm
    - name: Install dependencies
      id: install-dependencies
      run: npm ci
    - name: ESLint check
      id: eslint
      run: npm run lint
    - name: Run tests
      id: tests
      run: npm test
    - name: Build and Publish to Oxygen
      id: deploy
      run: npx shopify hydrogen deploy
      env:
        SHOPIFY_HYDROGEN_DEPLOYMENT_TOKEN: "${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_622885 }}"

